# Gradle Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# NeoForge Properties
# check these on https://projects.neoforged.net/neoforged/neoforge
minecraft_version = 26.1.2
neoforge_version = 26.1.2.95

# Mod Properties
mod_version = 1.2.1
maven_group = network.azusake
archives_base_name = halo
