# Gradle / Forge userdev
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=false

# Minecraft and Forge versions
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.0
forge_version_range=[47.4.0,48)
loader_version_range=[47,48)
mapping_channel=official
mapping_version=1.20.1

# Mod properties
mod_id=halo
mod_name=Halo Mod
mod_license=MIT
mod_version=1.3.0
maven_group=network.azusake
archives_base_name=halo
mod_authors=Azusa_Ke
mod_description=Halo ring rendering mod for Minecraft
