pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'halo'

if (!file('core/settings.gradle').isFile()) {
    throw new GradleException('HaloCore is missing. Run: git submodule update --init --recursive')
}
includeBuild('core')
