pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { name = 'MinecraftForge'; url = 'https://maven.minecraftforge.net/' }
        maven { name = 'SpongePowered'; url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
}

rootProject.name = 'halo'

if (!file('core/settings.gradle').isFile()) {
    throw new GradleException('HaloCore is missing. Run: git submodule update --init --recursive')
}
includeBuild('core')
