modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
logoFile="assets/halo/textures/halo/ring.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="halo.mixins.json"

[[mixins]]
config="halo-ysm.mixins.json"

[[dependencies.halo]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.halo]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.halo]]
modId="yes_steve_model"
type="optional"
versionRange="[2.6.5,2.6.6)"
ordering="AFTER"
side="CLIENT"
