modLoader="javafml"
loaderVersion="[3,]"
license="MIT"
logoFile="assets/halo/textures/halo/ring.png"

[[mods]]
    modId="halo"
    version="1.2.1"
    displayName="Halo Mod"
    description="Halo ring rendering mod for Minecraft"
    authors="Azusa_Ke"

[[dependencies.halo]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,26.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.halo]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.95,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="halo.mixins.json"

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[features.halo]
javaVersion="[25,)"
